version: "1"

databases:
  - name: worktracker-db
    databaseName: worktracker
    user: worktracker
    plan: free

services:
  api:
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        fromDatabase:
          name: worktracker-db
          property: connectionString

  # Note: Render cron jobs must be set up manually via dashboard
  # The API endpoint /admin/send-weekly-report is ready to be called
  # Use external cron service or Render's cron job feature
